export const CONSTANTS = {
  TOGGLE: 'Toggle',
  PHONE_CODE: 91,

  CURRENT: 'Current',
}

export const LABELS = {
  HOME: 'Home',
  ABOUT_ME: 'About me',
  PROJECT: 'Project',
  PROJECTS: 'Projects',
  SKILLS: 'Skills',
  EXPERIENCE: 'Experience',
  CONTACT: 'Contact',
  RESUME: 'Resume',
  LINKEDIN: 'LinkedIn',
  GITHUB: 'GitHub',
  WHATSAPP: 'WhatsApp',
  TELEGRAM: 'Telegram',
  EMAIL: 'Email',
}

export const TECHNOLOGIES = {
  HTML: 'HTML',
  CSS: 'CSS',
  SASS: 'Sass',
  JAVASCRIPT: 'JavaScript',
  TYPESCRIPT: 'TypeScript',
  REACT: 'React',
  NEXTJS: 'Next.js',
  TAILWIND_CSS: 'Tailwind CSS',
  MATERIAL_UI: 'Material-UI',
  CHAKRA_UI: 'Chakra UI',
  ANT_UI: 'Ant UI',
  SHADCN: 'ShadCn UI',
  REDUX: 'Redux',
  ZUSTAND: 'Zustand',
  GRAPHQL: 'GraphQL',
  APOLLO: 'Apollo Client',
  NODE_JS: 'Node.js',
  EXPRESS: 'Express.js',
  NESTJS: 'NestJS',
  MONGODB: 'MongoDB',
  POSTGRESQL: 'PostgreSQL',
  MYSQL: 'MySQL',
  SQLITE: 'SQLite',
  REDIS: 'Redis',
  ELASTICSEARCH: 'Elasticsearch',
  FIREBASE: 'Firebase',
  DYNAMODB: 'DynamoDB',
  AWS_EC2: 'Amazon EC2',
  AWS_S3: 'Amazon S3',
  AWS_LAMBDA: 'AWS Lambda',
  AWS_API_GATEWAY: 'AWS API Gateway',
  AWS_CLOUDFRONT: 'Amazon CloudFront',
  AWS_RDS: 'Amazon RDS',
  AWS_ELASTIC_BEANSTALK: 'AWS Elastic Beanstalk',
  AWS_CLOUDWATCH: 'Amazon CloudWatch',
  AWS_IAM: 'AWS IAM',
  VS_CODE: 'Visual Studio Code',
  WEBSTORM: 'WebStorm',
  POSTMAN: 'Postman',
  SWAGGER: 'Swagger',
  INSOMNIA: 'Insomnia',
  DOCKER: 'Docker',
  KUBERNETES: 'Kubernetes',
  GIT: 'Git',
  GITHUB: 'GitHub',
  GITLAB: 'GitLab',
  BIBUCKET: 'Bitbucket',
  JIRA: 'Jira',
  ESLINT: 'ESLint',
  PRETTIER: 'Prettier',
  JEST: 'Jest',
  HUGGING_FACE: 'Hugging Face',
  GENERATIVE_AI: 'Generative AI',
  OPENAI: 'OpenAI',
}
