export const VALUES = {
  // Layout
  HEADER_HEIGHT: 72,
  LAYOUT_PADDING: 72,
  BACKDROP_BLUR: 5,
  SCROLL_THRESHOLD: 100,
  SOCIAL_ICON_SIZE: 28,
  ILLUSTRATION_WIDTH: 500,
  ILLUSTRATION_RATIO: 1.1789394261,
  PROJECT_CARD_HEIGHT: 680,
  COMPANY_LEFT_SECTION_WIDTH: 48,
  SKILL_ICON_CONTAINER_WIDTH: 60,
  SKILL_ICON_WIDTH: 52,
  FADE_IN_UP_DURATION: 0.8,
  STAGGER_CHILDREN_DURATION: 0.2,
  ABOUT_STAGGER_CHILDREN_DURATION: 0.25,
  SKILLS_STAGGER_CHILDREN_DURATION: 0.1,
  ICON_SIZE: 24,
  ICON_COLOR: 'var(--primary)',

  PHONE_CODE: 91,
  PADDING_CLASS: 'px-4 md:px-8 lg:px-16 xl:px-20 2xl:px-28',
  SKILL_CARD_HEIGHT_CLASS: 'h-[132px] phone:h-[100px]',
}
